version: '3'
services:
  book_catalog:
    image: book_catalog:v1
    build: 
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book_catalog
    environment:
      - PORT=7000
      - DATABASE_URL=postgresql://thoufiya_sit722_part3_fgz4_user:gO06rHRjQ3R7TTT1iNrIp0txA6OHUXsq@dpg-crom97q3esus73c3g1h0-a.oregon-postgres.render.com/thoufiya_sit722_part3_fgz4

  inventory_management:
    image: inventory_management:v1
    build: 
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory_management
    environment:
      - PORT=7001
      - DATABASE_URL=postgresql://thoufiya_sit722_part3_fgz4_user:gO06rHRjQ3R7TTT1iNrIp0txA6OHUXsq@dpg-crom97q3esus73c3g1h0-a.oregon-postgres.render.com/thoufiya_sit722_part3_fgz4